name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
      
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ws-server:latest ./server

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ws-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Docker Image on Runner
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/ws-server:latest
          docker stop ws-server-container || true
          docker rm ws-server-container || true
          docker run -d --name ws-server-container -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/ws-server:latest
